### ISSUE TITLE
Tracker: 0.14 release

### ISSUE THREAD

**Issue by vks** [statrs-dev/statrs#140]
@troublescooter Here is the list of items that I think should be in the 0.15 release. Please feel free to edit the list.

## Required items
- [x] Upgrade to Rand 0.8
- [x] Fix doctests (#139)
- [x] Update changelog

## Optional items
- [ ] Migrate CI to GitHub actions (or elsewhere) (#130)
- [ ] Specialize inverse_cdf for LogNormal distribution (#127, needs review)
- [ ] Ideal and robust soliton distribution (#119, waits on author)
- [ ] Refactor chi-squared distribution (#77, waits on author)

I started updating the changelog in #139, but it's very incomplete. @troublescooter I think you have the best overview of the changes since the last release. Do you think you could give it a try? Thanks!

**Comment by vks** [comment]
@troublescooter What do you think about releasing 0.14 now?

**Comment by troublescooter** [comment]
I think that would be a good idea.

**Comment by vks** [comment]
Thanks!
